import type { Unit, Review } from "./types.ts";

export const FACULTY_MAP: Record<string, { short: string; color: string; bg: string }> = {
  "Faculty of Information Technology": { short: "FIT", color: "text-blue-700",    bg: "bg-blue-50"    },
  "Faculty of Science":                { short: "SCI", color: "text-emerald-700", bg: "bg-emerald-50"  },
  "Faculty of Business & Economics":   { short: "BUS", color: "text-amber-700",   bg: "bg-amber-50"   },
  "Faculty of Engineering":            { short: "ENG", color: "text-purple-700",  bg: "bg-purple-50"  },
  "Faculty of Arts":                   { short: "ART", color: "text-rose-700",    bg: "bg-rose-50"    },
  "Faculty of Law":                    { short: "LAW", color: "text-slate-700",   bg: "bg-slate-100"  },
};

export function diffLabel(d: number) {
  return (["","Very Easy","Easy","Medium","Hard","Very Hard"] as const)[d] ?? "—";
}

export function ratingColor(r: number) {
  if (r >= 4.2) return "#15803d";
  if (r >= 3.5) return "#a16207";
  if (r >= 2.5) return "#c2410c";
  return "#b91c1c";
}

export const UNITS: Unit[] = [
  // ── FIT — Software Systems & Cybersecurity ──
  { code:"FIT1045", name:"Introduction to algorithms and programming", faculty:"Faculty of Information Technology", school:"Software Systems & Cybersecurity", level:1, creditPoints:6, semesters:["S1","S2","Summer"], campuses:["Clayton","Malaysia"], rating:3.8, reviewCount:248, difficulty:3, workload:"Moderate", description:"Foundational programming using Python. Covers algorithmic thinking, data types, control structures, functions, and problem decomposition.", tags:["python","algorithms","first-year","summer-available"] },
  { code:"FIT1047", name:"Introduction to computer organisation and architecture", faculty:"Faculty of Information Technology", school:"Software Systems & Cybersecurity", level:1, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton","Malaysia"], rating:3.4, reviewCount:89, difficulty:3, workload:"Moderate", description:"Digital logic, CPU architecture, assembly language, and memory organisation. Foundational hardware knowledge for software engineers.", tags:["hardware","assembly","architecture","first-year"] },
  { code:"FIT1048", name:"Fundamentals of C++", faculty:"Faculty of Information Technology", school:"Software Systems & Cybersecurity", level:1, creditPoints:6, semesters:["S1"], campuses:["Clayton"], rating:3.6, reviewCount:61, difficulty:3, workload:"Moderate", description:"C++ fundamentals through to object-oriented programming, pointers, and memory management.", tags:["c++","oop","memory","s1-only","clayton-only"] },
  { code:"FIT1051", name:"Programming fundamentals in Java", faculty:"Faculty of Information Technology", school:"Software Systems & Cybersecurity", level:1, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.5, reviewCount:104, difficulty:3, workload:"Moderate", description:"Object-oriented programming in Java covering classes, inheritance, interfaces, exception handling, and basic data structures.", tags:["java","oop","programming","first-year","clayton-only"] },
  { code:"FIT2004", name:"Algorithms and data structures", faculty:"Faculty of Information Technology", school:"Software Systems & Cybersecurity", level:2, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton","Malaysia"], rating:4.3, reviewCount:182, difficulty:5, workload:"Heavy", description:"Core CS unit: sorting, graph algorithms, dynamic programming, greedy methods, and complexity analysis. Essential for technical interviews.", tags:["algorithms","graphs","complexity","competitive-programming"] },
  { code:"FIT2099", name:"Object-oriented design and implementation", faculty:"Faculty of Information Technology", school:"Software Systems & Cybersecurity", level:2, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton","Malaysia"], rating:3.9, reviewCount:137, difficulty:3, workload:"Moderate", description:"Design patterns, SOLID principles, UML modelling, and clean code practices in Java.", tags:["java","design-patterns","oop","uml"] },
  { code:"FIT2100", name:"Operating systems", faculty:"Faculty of Information Technology", school:"Software Systems & Cybersecurity", level:2, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.7, reviewCount:98, difficulty:4, workload:"Heavy", description:"Processes, threads, scheduling, memory management, file systems, and concurrency. Labs in C on Unix.", tags:["os","c","unix","concurrency","clayton-only"] },
  { code:"FIT2101", name:"Software engineering process and management", faculty:"Faculty of Information Technology", school:"Software Systems & Cybersecurity", level:2, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.3, reviewCount:76, difficulty:2, workload:"Moderate", description:"Agile and waterfall methodologies, project planning, risk management, and software quality assurance.", tags:["agile","project-management","scrum","clayton-only"] },
  { code:"FIT3155", name:"Advanced data structures and algorithms", faculty:"Faculty of Information Technology", school:"Software Systems & Cybersecurity", level:3, creditPoints:6, semesters:["S2"], campuses:["Clayton"], rating:4.4, reviewCount:44, difficulty:5, workload:"Heavy", description:"Advanced string algorithms, suffix arrays, network flows, matching algorithms, and approximation algorithms.", tags:["algorithms","strings","advanced","s2-only","clayton-only"] },
  { code:"FIT3161", name:"Computer science project part 1", faculty:"Faculty of Information Technology", school:"Software Systems & Cybersecurity", level:3, creditPoints:6, semesters:["S1"], campuses:["Clayton"], rating:3.9, reviewCount:55, difficulty:3, workload:"Heavy", description:"Research-oriented project proposing and beginning a substantial CS project under academic supervision.", tags:["project","research","capstone","s1-only","clayton-only"] },
  { code:"FIT3162", name:"Computer science project part 2", faculty:"Faculty of Information Technology", school:"Software Systems & Cybersecurity", level:3, creditPoints:6, semesters:["S2"], campuses:["Clayton"], rating:4.0, reviewCount:48, difficulty:3, workload:"Heavy", description:"Continuation and completion of the CS project started in FIT3161. Includes final report and presentation.", tags:["project","research","capstone","s2-only","clayton-only"] },
  { code:"FIT3170", name:"Software engineering practice", faculty:"Faculty of Information Technology", school:"Software Systems & Cybersecurity", level:3, creditPoints:12, semesters:["S1","S2"], campuses:["Clayton"], rating:4.5, reviewCount:121, difficulty:3, workload:"Heavy", description:"Year-long 12-credit capstone with a real industry client using agile. The closest to real industry experience at Monash.", tags:["capstone","agile","industry","team","12-credit-points","clayton-only"] },
  { code:"FIT3176", name:"Engineering distributed systems", faculty:"Faculty of Information Technology", school:"Software Systems & Cybersecurity", level:3, creditPoints:6, semesters:["S1"], campuses:["Clayton"], rating:3.7, reviewCount:36, difficulty:3, workload:"Moderate", description:"Distributed computing principles, microservices, cloud architectures, containerisation with Docker, and Kubernetes orchestration.", tags:["distributed","cloud","docker","microservices","s1-only","clayton-only"] },

  // ── FIT — Data Science & AI ──
  { code:"FIT2014", name:"Theory of computation", faculty:"Faculty of Information Technology", school:"Data Science & AI", level:2, creditPoints:6, semesters:["S1"], campuses:["Clayton"], rating:3.6, reviewCount:67, difficulty:4, workload:"Moderate", description:"Automata theory, formal languages, Turing machines, decidability, and computational complexity (P and NP).", tags:["theory","turing","complexity","maths","s1-only","clayton-only"] },
  { code:"FIT3047", name:"Intelligent systems", faculty:"Faculty of Information Technology", school:"Data Science & AI", level:3, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.8, reviewCount:79, difficulty:3, workload:"Moderate", description:"Search algorithms, knowledge representation, machine learning fundamentals, and neural networks.", tags:["ai","ml","search","neural-networks","clayton-only"] },
  { code:"FIT3094", name:"AI, agents and environments", faculty:"Faculty of Information Technology", school:"Data Science & AI", level:3, creditPoints:6, semesters:["S2"], campuses:["Clayton"], rating:4.0, reviewCount:52, difficulty:3, workload:"Moderate", description:"Multi-agent systems, reinforcement learning, planning, and agent architectures.", tags:["ai","agents","reinforcement-learning","s2-only","clayton-only"] },
  { code:"FIT3139", name:"Computational science", faculty:"Faculty of Information Technology", school:"Data Science & AI", level:3, creditPoints:6, semesters:["S2"], campuses:["Clayton"], rating:3.5, reviewCount:31, difficulty:4, workload:"Heavy", description:"Numerical methods, scientific computing, simulation, and performance optimisation.", tags:["numerical","scientific","simulation","s2-only","clayton-only"] },
  { code:"FIT3143", name:"Parallel computing", faculty:"Faculty of Information Technology", school:"Data Science & AI", level:3, creditPoints:6, semesters:["S2"], campuses:["Clayton"], rating:3.5, reviewCount:42, difficulty:4, workload:"Heavy", description:"Parallel algorithm design, MPI, OpenMP, shared/distributed memory, and GPU computing with CUDA.", tags:["parallel","cuda","mpi","hpc","s2-only","clayton-only"] },
  { code:"FIT3171", name:"Databases and information management", faculty:"Faculty of Information Technology", school:"Data Science & AI", level:3, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.8, reviewCount:58, difficulty:3, workload:"Moderate", description:"Advanced databases: transactions, query optimisation, NoSQL, data warehousing, and big data technologies.", tags:["databases","nosql","data-warehouse","clayton-only"] },
  { code:"FIT3179", name:"Data visualisation", faculty:"Faculty of Information Technology", school:"Data Science & AI", level:3, creditPoints:6, semesters:["S2"], campuses:["Clayton"], rating:4.1, reviewCount:67, difficulty:2, workload:"Moderate", description:"Principles of data visualisation, D3.js, Vega-Lite, dashboard design, and visual analytics.", tags:["data-viz","d3","vega","visualisation","s2-only","clayton-only"] },

  // ── FIT — Human-Centred Computing ──
  { code:"FIT1049", name:"IT professional practice", faculty:"Faculty of Information Technology", school:"Human-Centred Computing", level:1, creditPoints:6, semesters:["S1","S2","Summer"], campuses:["Clayton","Malaysia"], rating:3.0, reviewCount:201, difficulty:1, workload:"Light", description:"Ethics, communication, teamwork, and professional practice in IT. Mostly essay-based with group presentations.", tags:["ethics","professional","soft-skills","summer-available"] },
  { code:"FIT2001", name:"Systems development", faculty:"Faculty of Information Technology", school:"Human-Centred Computing", level:2, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.4, reviewCount:88, difficulty:3, workload:"Moderate", description:"Systems analysis, requirements elicitation, UML, prototyping, and SDLC methodologies.", tags:["systems-analysis","uml","requirements","clayton-only"] },
  { code:"FIT2002", name:"IT project management", faculty:"Faculty of Information Technology", school:"Human-Centred Computing", level:2, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.2, reviewCount:94, difficulty:2, workload:"Light", description:"Project planning, scheduling, risk management, cost estimation, and IT governance using PMBOK.", tags:["project-management","pmbok","planning","clayton-only"] },
  { code:"FIT3088", name:"Computer graphics", faculty:"Faculty of Information Technology", school:"Human-Centred Computing", level:3, creditPoints:6, semesters:["S1"], campuses:["Clayton"], rating:4.1, reviewCount:47, difficulty:4, workload:"Heavy", description:"OpenGL/WebGL, 3D transformations, rasterisation, ray tracing, and shader programming.", tags:["graphics","opengl","3d","shaders","s1-only","clayton-only"] },
  { code:"FIT3175", name:"Usability", faculty:"Faculty of Information Technology", school:"Human-Centred Computing", level:3, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:4.0, reviewCount:63, difficulty:2, workload:"Light", description:"User-centred design, heuristic evaluation, usability testing, wireframing, and accessibility.", tags:["ux","hci","usability","design","clayton-only"] },

  // ── FIT — Networks & Cybersecurity ──
  { code:"FIT2093", name:"Introduction to cybersecurity", faculty:"Faculty of Information Technology", school:"Networks & Cybersecurity", level:2, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.9, reviewCount:113, difficulty:3, workload:"Moderate", description:"Security fundamentals: cryptography, network security, web security, malware analysis, and ethical hacking basics.", tags:["security","cryptography","networking","ethical-hacking","clayton-only"] },
  { code:"FIT2094", name:"Databases", faculty:"Faculty of Information Technology", school:"Networks & Cybersecurity", level:2, creditPoints:6, semesters:["S1","S2","Summer"], campuses:["Clayton","Malaysia"], rating:4.1, reviewCount:155, difficulty:3, workload:"Moderate", description:"Relational database design, ER modelling, SQL, normalisation, and transaction management.", tags:["sql","databases","erd","normalisation","summer-available"] },
  { code:"FIT3031", name:"Network security", faculty:"Faculty of Information Technology", school:"Networks & Cybersecurity", level:3, creditPoints:6, semesters:["S2"], campuses:["Clayton"], rating:3.9, reviewCount:39, difficulty:4, workload:"Heavy", description:"Advanced network protocols, firewall design, intrusion detection, VPNs, PKI, and secure network architecture.", tags:["networking","security","firewall","vpn","s2-only","clayton-only"] },
  { code:"FIT3173", name:"Software security", faculty:"Faculty of Information Technology", school:"Networks & Cybersecurity", level:3, creditPoints:6, semesters:["S1"], campuses:["Clayton"], rating:4.2, reviewCount:48, difficulty:4, workload:"Heavy", description:"Secure coding, vulnerability analysis, penetration testing, reverse engineering, and exploit development. CTF-style assignments.", tags:["security","pentest","ctf","exploit","s1-only","clayton-only"] },

  // ── Science — Mathematics ──
  { code:"MTH1010", name:"Functions and their applications", faculty:"Faculty of Science", school:"School of Mathematics", level:1, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.1, reviewCount:132, difficulty:3, workload:"Moderate", description:"Foundational unit covering functions, trigonometry, exponentials, logarithms, and an introduction to calculus.", tags:["maths","calculus","functions","first-year","bridging","clayton-only"] },
  { code:"MTH1020", name:"Analysis of change", faculty:"Faculty of Science", school:"School of Mathematics", level:1, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.3, reviewCount:118, difficulty:3, workload:"Moderate", description:"Differentiation and integration with applications to rates of change, optimisation, and area.", tags:["calculus","differentiation","integration","first-year","clayton-only"] },
  { code:"MTH1030", name:"Techniques for modelling", faculty:"Faculty of Science", school:"School of Mathematics", level:1, creditPoints:6, semesters:["S1","S2","Summer"], campuses:["Clayton","Malaysia"], rating:3.2, reviewCount:167, difficulty:3, workload:"Moderate", description:"Calculus, differential equations, and linear algebra applied to real-world modelling. Core maths for engineering and science.", tags:["calculus","differential-equations","linear-algebra","first-year","summer-available"] },
  { code:"MTH1035", name:"Techniques for modelling (advanced)", faculty:"Faculty of Science", school:"School of Mathematics", level:1, creditPoints:6, semesters:["S1"], campuses:["Clayton"], rating:3.9, reviewCount:45, difficulty:4, workload:"Heavy", description:"Accelerated version of MTH1030 for students with strong high-school maths.", tags:["calculus","advanced","proof","s1-only","clayton-only"] },
  { code:"MTH2010", name:"Multivariable calculus", faculty:"Faculty of Science", school:"School of Mathematics", level:2, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.4, reviewCount:98, difficulty:4, workload:"Heavy", description:"Partial derivatives, multiple integrals, vector fields, line and surface integrals, and theorems of Gauss, Green, and Stokes.", tags:["calculus","vector-fields","multivariable","clayton-only"] },
  { code:"MTH2021", name:"Linear algebra with applications", faculty:"Faculty of Science", school:"School of Mathematics", level:2, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.7, reviewCount:112, difficulty:3, workload:"Moderate", description:"Vector spaces, linear transformations, eigenvalues and eigenvectors, with applications in graphics, stats, and ML.", tags:["linear-algebra","eigenvectors","matrices","clayton-only"] },
  { code:"MTH2032", name:"Differential equations with modelling", faculty:"Faculty of Science", school:"School of Mathematics", level:2, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.5, reviewCount:84, difficulty:4, workload:"Heavy", description:"Ordinary differential equations, systems of ODEs, Laplace transforms, and numerical methods.", tags:["differential-equations","laplace","ode","clayton-only"] },
  { code:"MTH2040", name:"Real analysis", faculty:"Faculty of Science", school:"School of Mathematics", level:2, creditPoints:6, semesters:["S2"], campuses:["Clayton"], rating:3.6, reviewCount:52, difficulty:4, workload:"Heavy", description:"Rigorous analysis of limits, continuity, differentiation, and integration. Introduction to mathematical proof.", tags:["analysis","proof","rigorous","maths","s2-only","clayton-only"] },
  { code:"STA1010", name:"Statistical methods for science", faculty:"Faculty of Science", school:"School of Mathematics", level:1, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton","Malaysia"], rating:3.5, reviewCount:143, difficulty:2, workload:"Light", description:"Descriptive statistics, probability, hypothesis testing, regression, and ANOVA using R.", tags:["statistics","r","probability","data","first-year"] },
  { code:"STA2216", name:"Data analysis for science", faculty:"Faculty of Science", school:"School of Mathematics", level:2, creditPoints:6, semesters:["S2"], campuses:["Clayton"], rating:3.6, reviewCount:61, difficulty:3, workload:"Moderate", description:"Applied statistical modelling using R: linear models, ANOVA, logistic regression, time series, and data wrangling.", tags:["statistics","r","regression","data-science","s2-only","clayton-only"] },

  // ── Science — Physics ──
  { code:"PHY1011", name:"Physics 1", faculty:"Faculty of Science", school:"School of Physics & Astronomy", level:1, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton","Malaysia"], rating:3.6, reviewCount:341, difficulty:4, workload:"Heavy", description:"Classical mechanics, thermodynamics, waves, and introductory electromagnetism. Weekly compulsory labs.", tags:["mechanics","thermodynamics","waves","labs","first-year"] },
  { code:"PHY1022", name:"Physics 2", faculty:"Faculty of Science", school:"School of Physics & Astronomy", level:1, creditPoints:6, semesters:["S2"], campuses:["Clayton"], rating:3.4, reviewCount:178, difficulty:4, workload:"Heavy", description:"Electromagnetism, optics, quantum physics, and special relativity.", tags:["electromagnetism","quantum","optics","s2-only","clayton-only"] },
  { code:"PHY2011", name:"Quantum and classical dynamics", faculty:"Faculty of Science", school:"School of Physics & Astronomy", level:2, creditPoints:6, semesters:["S1"], campuses:["Clayton"], rating:3.5, reviewCount:67, difficulty:4, workload:"Heavy", description:"Lagrangian and Hamiltonian mechanics, introductory quantum mechanics, wave functions, and the Schrödinger equation.", tags:["quantum","mechanics","lagrangian","s1-only","clayton-only"] },
  { code:"PHY2022", name:"Electromagnetism and optics", faculty:"Faculty of Science", school:"School of Physics & Astronomy", level:2, creditPoints:6, semesters:["S2"], campuses:["Clayton"], rating:3.4, reviewCount:54, difficulty:4, workload:"Heavy", description:"Maxwell's equations, electromagnetic waves, polarisation, interference, diffraction, and optical instruments.", tags:["electromagnetism","maxwells","optics","s2-only","clayton-only"] },

  // ── Science — Chemistry ──
  { code:"CHM1011", name:"Chemistry 1", faculty:"Faculty of Science", school:"School of Chemistry", level:1, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton","Malaysia"], rating:3.3, reviewCount:255, difficulty:4, workload:"Heavy", description:"Atomic structure, chemical bonding, stoichiometry, thermochemistry, and introductory organic chemistry. Weekly labs.", tags:["chemistry","organic","bonding","labs","first-year"] },
  { code:"CHM1022", name:"Chemistry 2", faculty:"Faculty of Science", school:"School of Chemistry", level:1, creditPoints:6, semesters:["S2"], campuses:["Clayton"], rating:3.2, reviewCount:134, difficulty:4, workload:"Heavy", description:"Equilibria, electrochemistry, kinetics, and further organic chemistry.", tags:["chemistry","equilibria","kinetics","organic","s2-only","clayton-only"] },
  { code:"CHM2911", name:"Organic chemistry", faculty:"Faculty of Science", school:"School of Chemistry", level:2, creditPoints:6, semesters:["S1"], campuses:["Clayton"], rating:3.4, reviewCount:78, difficulty:4, workload:"Heavy", description:"Reaction mechanisms, functional group chemistry, stereochemistry, and spectroscopic identification.", tags:["organic","chemistry","mechanisms","spectroscopy","s1-only","clayton-only"] },
  { code:"CHM2922", name:"Physical chemistry", faculty:"Faculty of Science", school:"School of Chemistry", level:2, creditPoints:6, semesters:["S2"], campuses:["Clayton"], rating:3.3, reviewCount:62, difficulty:4, workload:"Heavy", description:"Thermodynamics, kinetics, quantum chemistry, and spectroscopy.", tags:["physical-chemistry","thermodynamics","quantum","s2-only","clayton-only"] },

  // ── Science — Biology ──
  { code:"BIO1011", name:"Biology 1", faculty:"Faculty of Science", school:"School of Biological Sciences", level:1, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton","Malaysia"], rating:3.7, reviewCount:198, difficulty:3, workload:"Moderate", description:"Cell biology, genetics, evolution, ecology, and biodiversity. Weekly labs include microscopy and dissection.", tags:["cell-biology","genetics","evolution","labs","first-year"] },
  { code:"BIO1022", name:"Biology 2", faculty:"Faculty of Science", school:"School of Biological Sciences", level:1, creditPoints:6, semesters:["S2"], campuses:["Clayton"], rating:3.5, reviewCount:143, difficulty:3, workload:"Moderate", description:"Plant biology, physiology, animal diversity, ecology, and environmental biology.", tags:["plant-biology","ecology","physiology","labs","s2-only","clayton-only"] },
  { code:"BIO2011", name:"Cell biology and genetics", faculty:"Faculty of Science", school:"School of Biological Sciences", level:2, creditPoints:6, semesters:["S1"], campuses:["Clayton"], rating:3.5, reviewCount:87, difficulty:3, workload:"Moderate", description:"Molecular cell biology, gene expression, DNA replication, and cell signalling.", tags:["molecular-biology","genetics","dna","s1-only","clayton-only"] },
  { code:"BIO2042", name:"Biochemistry and molecular biology", faculty:"Faculty of Science", school:"School of Biological Sciences", level:2, creditPoints:6, semesters:["S2"], campuses:["Clayton"], rating:3.4, reviewCount:73, difficulty:4, workload:"Heavy", description:"Protein structure and function, enzyme kinetics, metabolism, DNA replication, and gene expression.", tags:["biochemistry","proteins","enzymes","metabolism","s2-only","clayton-only"] },

  // ── Business — Economics ──
  { code:"ECF1100", name:"Microeconomics", faculty:"Faculty of Business & Economics", school:"Department of Economics", level:1, creditPoints:6, semesters:["S1","S2","Summer"], campuses:["Clayton","Malaysia"], rating:4.0, reviewCount:312, difficulty:2, workload:"Light", description:"Supply and demand, elasticity, market structures, consumer theory, and welfare analysis.", tags:["microeconomics","markets","first-year","summer-available"] },
  { code:"ECF1200", name:"Macroeconomics", faculty:"Faculty of Business & Economics", school:"Department of Economics", level:1, creditPoints:6, semesters:["S1","S2","Summer"], campuses:["Clayton","Malaysia"], rating:3.8, reviewCount:276, difficulty:2, workload:"Light", description:"GDP, inflation, unemployment, monetary and fiscal policy, and international trade.", tags:["macroeconomics","gdp","policy","first-year","summer-available"] },
  { code:"ECF2121", name:"Intermediate microeconomics", faculty:"Faculty of Business & Economics", school:"Department of Economics", level:2, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.6, reviewCount:71, difficulty:3, workload:"Moderate", description:"Consumer and producer theory at an intermediate mathematical level, game theory, and market failures.", tags:["microeconomics","game-theory","intermediate","clayton-only"] },
  { code:"ECF2211", name:"Intermediate macroeconomics", faculty:"Faculty of Business & Economics", school:"Department of Economics", level:2, creditPoints:6, semesters:["S2"], campuses:["Clayton"], rating:3.5, reviewCount:58, difficulty:3, workload:"Moderate", description:"IS-LM model, aggregate demand and supply, open economy macroeconomics, and business cycle theory.", tags:["macroeconomics","is-lm","open-economy","s2-only","clayton-only"] },
  { code:"ECF2731", name:"Applied econometrics", faculty:"Faculty of Business & Economics", school:"Department of Economics", level:2, creditPoints:6, semesters:["S1"], campuses:["Clayton"], rating:3.5, reviewCount:64, difficulty:3, workload:"Moderate", description:"Regression analysis, hypothesis testing, time series models, and panel data methods using Stata.", tags:["econometrics","statistics","stata","regression","s1-only","clayton-only"] },

  // ── Business — Accounting ──
  { code:"ACC1100", name:"Introduction to financial accounting", faculty:"Faculty of Business & Economics", school:"Department of Accounting", level:1, creditPoints:6, semesters:["S1","S2","Summer"], campuses:["Clayton","Malaysia"], rating:3.7, reviewCount:287, difficulty:3, workload:"Moderate", description:"Accounting cycle, financial statements, double-entry bookkeeping, and basic financial analysis.", tags:["accounting","financial-statements","bookkeeping","first-year","summer-available"] },
  { code:"ACC2100", name:"Management accounting", faculty:"Faculty of Business & Economics", school:"Department of Accounting", level:2, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton","Malaysia"], rating:3.6, reviewCount:142, difficulty:3, workload:"Moderate", description:"Cost behaviour, budgeting, variance analysis, and decision-making tools for internal management.", tags:["management-accounting","costing","budgeting"] },
  { code:"ACC3100", name:"Financial accounting theory", faculty:"Faculty of Business & Economics", school:"Department of Accounting", level:3, creditPoints:6, semesters:["S1"], campuses:["Clayton"], rating:3.4, reviewCount:55, difficulty:3, workload:"Moderate", description:"Accounting theory, IFRS standards, conceptual frameworks, and critical analysis of financial reporting.", tags:["accounting","ifrs","theory","s1-only","clayton-only"] },
  { code:"BTF2700", name:"Business law I", faculty:"Faculty of Business & Economics", school:"Department of Accounting", level:2, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton","Malaysia"], rating:3.7, reviewCount:121, difficulty:2, workload:"Light", description:"Contract law, tort law, and the Australian legal system. Highly relevant for business and accounting students.", tags:["business-law","contract","tort","legal"] },

  // ── Business — Finance ──
  { code:"FIN2101", name:"Business finance", faculty:"Faculty of Business & Economics", school:"Department of Finance", level:2, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton","Malaysia"], rating:3.9, reviewCount:198, difficulty:3, workload:"Moderate", description:"Time value of money, capital budgeting, risk and return, portfolio theory, and capital structure.", tags:["finance","valuation","investment","npv"] },
  { code:"BFC2140", name:"Futures and options", faculty:"Faculty of Business & Economics", school:"Department of Finance", level:2, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.8, reviewCount:89, difficulty:3, workload:"Moderate", description:"Derivative instruments, options pricing (Black-Scholes), hedging strategies, and futures markets.", tags:["derivatives","options","futures","black-scholes","clayton-only"] },
  { code:"BFC3240", name:"Investments", faculty:"Faculty of Business & Economics", school:"Department of Finance", level:3, creditPoints:6, semesters:["S1"], campuses:["Clayton"], rating:3.9, reviewCount:67, difficulty:3, workload:"Moderate", description:"Portfolio theory, CAPM, market efficiency, fixed income, and equity valuation.", tags:["investments","portfolio","capm","equity","s1-only","clayton-only"] },

  // ── Business — Marketing ──
  { code:"MKT1120", name:"Marketing fundamentals", faculty:"Faculty of Business & Economics", school:"Department of Marketing", level:1, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton","Malaysia"], rating:3.9, reviewCount:223, difficulty:2, workload:"Light", description:"Segmentation, targeting, positioning, the marketing mix, consumer behaviour overview, and digital marketing.", tags:["marketing","branding","consumer","first-year"] },
  { code:"MKT2100", name:"Consumer behaviour", faculty:"Faculty of Business & Economics", school:"Department of Marketing", level:2, creditPoints:6, semesters:["S2"], campuses:["Clayton","Malaysia"], rating:3.8, reviewCount:89, difficulty:2, workload:"Light", description:"Psychological and social influences on buying decisions, decision models, and applications to marketing strategy.", tags:["consumer","psychology","behaviour","marketing","s2-only"] },
  { code:"MKT3120", name:"Marketing strategy", faculty:"Faculty of Business & Economics", school:"Department of Marketing", level:3, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.7, reviewCount:76, difficulty:2, workload:"Moderate", description:"Strategic marketing planning, competitive analysis, brand management, and integrated marketing communications.", tags:["marketing","strategy","brand","competitive","clayton-only"] },

  // ── Business — Management ──
  { code:"MGF1010", name:"Introduction to management", faculty:"Faculty of Business & Economics", school:"Department of Management", level:1, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton","Malaysia"], rating:3.6, reviewCount:189, difficulty:1, workload:"Light", description:"Classical and contemporary management theory, organisational design, leadership, motivation, and change management.", tags:["management","leadership","organisation","first-year"] },
  { code:"MGF2661", name:"Organisational behaviour", faculty:"Faculty of Business & Economics", school:"Department of Management", level:2, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton","Malaysia"], rating:3.7, reviewCount:112, difficulty:2, workload:"Light", description:"Individual and group behaviour in organisations: motivation, leadership, team dynamics, culture, and change.", tags:["organisational-behaviour","leadership","teams","hr"] },
  { code:"MGF3681", name:"Strategic management", faculty:"Faculty of Business & Economics", school:"Department of Management", level:3, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.8, reviewCount:94, difficulty:2, workload:"Moderate", description:"Strategy formulation, competitive advantage, Porter's Five Forces, resource-based view, and strategic implementation.", tags:["strategy","competitive-advantage","porter","clayton-only"] },

  // ── Engineering ──
  { code:"ENG1001", name:"Engineering design: cleaner production", faculty:"Faculty of Engineering", school:"Mechanical & Aerospace Engineering", level:1, creditPoints:6, semesters:["S1"], campuses:["Clayton"], rating:3.7, reviewCount:124, difficulty:2, workload:"Moderate", description:"Engineering design methodology, sustainability, and teamwork. Project-based with prototyping and presentations.", tags:["design","teamwork","sustainability","first-year","s1-only","clayton-only"] },
  { code:"ENG1002", name:"Engineering design: engineering modelling", faculty:"Faculty of Engineering", school:"Mechanical & Aerospace Engineering", level:1, creditPoints:6, semesters:["S2"], campuses:["Clayton"], rating:3.5, reviewCount:98, difficulty:3, workload:"Moderate", description:"CAD, SolidWorks, finite element analysis basics, and technical drawing standards.", tags:["cad","solidworks","modelling","first-year","s2-only","clayton-only"] },
  { code:"MAE2403", name:"Engineering mechanics: dynamics", faculty:"Faculty of Engineering", school:"Mechanical & Aerospace Engineering", level:2, creditPoints:6, semesters:["S1"], campuses:["Clayton"], rating:3.3, reviewCount:67, difficulty:4, workload:"Heavy", description:"Kinematics and kinetics of particles and rigid bodies, work-energy methods, and vibrations.", tags:["dynamics","mechanics","kinematics","s1-only","clayton-only"] },
  { code:"MAE3404", name:"Fluid mechanics", faculty:"Faculty of Engineering", school:"Mechanical & Aerospace Engineering", level:3, creditPoints:6, semesters:["S2"], campuses:["Clayton"], rating:3.4, reviewCount:52, difficulty:4, workload:"Heavy", description:"Fluid statics and dynamics, Bernoulli's equation, pipe flow, boundary layers, and computational fluid dynamics intro.", tags:["fluid-mechanics","cfd","thermodynamics","s2-only","clayton-only"] },
  { code:"ECE2031", name:"Electrical engineering fundamentals", faculty:"Faculty of Engineering", school:"Electrical & Computer Systems Engineering", level:2, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.4, reviewCount:87, difficulty:4, workload:"Heavy", description:"Circuit analysis, AC/DC theory, op-amps, signals and systems, and introductory digital electronics.", tags:["circuits","electronics","signals","clayton-only"] },
  { code:"ECE3041", name:"Signals and systems", faculty:"Faculty of Engineering", school:"Electrical & Computer Systems Engineering", level:3, creditPoints:6, semesters:["S1"], campuses:["Clayton"], rating:3.5, reviewCount:49, difficulty:4, workload:"Heavy", description:"Continuous and discrete-time signals, Fourier transforms, Laplace transforms, Z-transforms, and filtering.", tags:["signals","fourier","laplace","dsp","s1-only","clayton-only"] },
  { code:"ECE4076", name:"Computer vision", faculty:"Faculty of Engineering", school:"Electrical & Computer Systems Engineering", level:4, creditPoints:6, semesters:["S1"], campuses:["Clayton"], rating:4.3, reviewCount:38, difficulty:4, workload:"Heavy", description:"Image processing, feature extraction, deep learning for vision, object detection, and 3D reconstruction.", tags:["computer-vision","deep-learning","image-processing","ai","s1-only","clayton-only"] },
  { code:"CIV2282", name:"Engineering materials and structures", faculty:"Faculty of Engineering", school:"Civil Engineering", level:2, creditPoints:6, semesters:["S1"], campuses:["Clayton"], rating:3.3, reviewCount:56, difficulty:3, workload:"Moderate", description:"Properties of engineering materials, structural analysis, load distribution, and beam theory.", tags:["structures","materials","civil","s1-only","clayton-only"] },
  { code:"CIV3283", name:"Structural analysis and design", faculty:"Faculty of Engineering", school:"Civil Engineering", level:3, creditPoints:6, semesters:["S2"], campuses:["Clayton"], rating:3.4, reviewCount:41, difficulty:4, workload:"Heavy", description:"Structural analysis methods, concrete and steel design to Australian standards.", tags:["structures","concrete","steel","design","s2-only","clayton-only"] },
  { code:"CHE2163", name:"Chemical engineering thermodynamics", faculty:"Faculty of Engineering", school:"Chemical Engineering", level:2, creditPoints:6, semesters:["S1"], campuses:["Clayton"], rating:3.2, reviewCount:48, difficulty:4, workload:"Heavy", description:"Laws of thermodynamics, phase equilibria, chemical equilibrium, and equation-of-state models.", tags:["thermodynamics","chemical","equilibria","s1-only","clayton-only"] },

  // ── Arts — Psychological Sciences ──
  { code:"PSY1011", name:"Introduction to psychological science A", faculty:"Faculty of Arts", school:"School of Psychological Sciences", level:1, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton","Malaysia"], rating:4.1, reviewCount:312, difficulty:2, workload:"Light", description:"Foundations of psychology: biological bases of behaviour, sensation, perception, consciousness, and learning.", tags:["psychology","cognition","behaviour","first-year"] },
  { code:"PSY1022", name:"Introduction to psychological science B", faculty:"Faculty of Arts", school:"School of Psychological Sciences", level:1, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton","Malaysia"], rating:4.0, reviewCount:278, difficulty:2, workload:"Light", description:"Social psychology, personality, development, abnormal psychology, and research methods overview.", tags:["psychology","social","personality","first-year"] },
  { code:"PSY2042", name:"Psychological research methods", faculty:"Faculty of Arts", school:"School of Psychological Sciences", level:2, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.5, reviewCount:134, difficulty:3, workload:"Moderate", description:"Research design, statistical analysis using SPSS, ethics in research, and scientific writing.", tags:["psychology","research-methods","spss","statistics","clayton-only"] },
  { code:"PSY2061", name:"Social and personality psychology", faculty:"Faculty of Arts", school:"School of Psychological Sciences", level:2, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:4.0, reviewCount:156, difficulty:2, workload:"Light", description:"Attitudes, social influence, group dynamics, personality theories, and applications to real-world behaviour.", tags:["psychology","social","personality","group-dynamics","clayton-only"] },
  { code:"PSY3032", name:"Abnormal psychology", faculty:"Faculty of Arts", school:"School of Psychological Sciences", level:3, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:4.2, reviewCount:189, difficulty:3, workload:"Moderate", description:"Classification, causes, and treatment of psychological disorders. Covers anxiety, mood, psychotic, and personality disorders.", tags:["psychology","abnormal","disorders","mental-health","clayton-only"] },
  { code:"PSY3136", name:"Cognitive psychology", faculty:"Faculty of Arts", school:"School of Psychological Sciences", level:3, creditPoints:6, semesters:["S2"], campuses:["Clayton"], rating:3.9, reviewCount:98, difficulty:3, workload:"Moderate", description:"Memory, attention, language, decision-making, and problem-solving from a cognitive science perspective.", tags:["psychology","cognition","memory","attention","s2-only","clayton-only"] },

  // ── Arts — Social Sciences & Humanities ──
  { code:"SOC1010", name:"Imagining society: an introduction to sociology", faculty:"Faculty of Arts", school:"School of Social Sciences", level:1, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.8, reviewCount:142, difficulty:2, workload:"Light", description:"Sociological imagination, class, gender, race, culture, and institutions. Excellent breadth unit.", tags:["sociology","society","culture","first-year","breadth","clayton-only"] },
  { code:"POL1010", name:"Introduction to politics", faculty:"Faculty of Arts", school:"School of Social Sciences", level:1, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.9, reviewCount:118, difficulty:2, workload:"Light", description:"Political institutions, ideologies, democracy, power, and global politics. Popular breadth unit.", tags:["politics","democracy","government","first-year","breadth","clayton-only"] },
  { code:"PHI1010", name:"Introduction to philosophy", faculty:"Faculty of Arts", school:"School of Philosophical, Historical & International Studies", level:1, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:4.0, reviewCount:134, difficulty:2, workload:"Light", description:"Core philosophical questions on knowledge, reality, ethics, and mind. Very popular breadth unit.", tags:["philosophy","ethics","logic","first-year","breadth","essay","clayton-only"] },
  { code:"ETW1000", name:"Writing and reasoning", faculty:"Faculty of Arts", school:"School of Languages, Literatures, Cultures & Linguistics", level:1, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.6, reviewCount:167, difficulty:1, workload:"Light", description:"Academic writing, argumentation, critical reading, and research skills. Highly recommended for building essay-writing ability.", tags:["writing","academic","essays","communication","first-year","breadth","clayton-only"] },

  // ── Law ──
  { code:"LAW1101", name:"Legal reasoning and research", faculty:"Faculty of Law", school:"Monash Law School", level:1, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.7, reviewCount:89, difficulty:3, workload:"Moderate", description:"Legal method, case analysis, statutory interpretation, and legal research skills. Foundation for all law study.", tags:["law","legal-research","legal-reasoning","first-year","clayton-only"] },
  { code:"LAW2101", name:"Constitutional law", faculty:"Faculty of Law", school:"Monash Law School", level:2, creditPoints:6, semesters:["S1"], campuses:["Clayton"], rating:3.6, reviewCount:72, difficulty:4, workload:"Heavy", description:"The Australian Constitution, separation of powers, federalism, and constitutional rights and freedoms.", tags:["law","constitutional","federalism","high-court","s1-only","clayton-only"] },
  { code:"LAW2111", name:"Criminal law and procedure", faculty:"Faculty of Law", school:"Monash Law School", level:2, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.8, reviewCount:94, difficulty:3, workload:"Moderate", description:"Elements of criminal liability, specific offences, defences, and criminal procedure in the Australian context.", tags:["law","criminal","procedure","defences","clayton-only"] },
  { code:"LAW3101", name:"Administrative law", faculty:"Faculty of Law", school:"Monash Law School", level:3, creditPoints:6, semesters:["S2"], campuses:["Clayton"], rating:3.5, reviewCount:58, difficulty:3, workload:"Moderate", description:"Judicial review, administrative tribunals, freedom of information, and accountability of government decision-making.", tags:["law","administrative","judicial-review","tribunals","s2-only","clayton-only"] },
  { code:"LAW3112", name:"Contract law", faculty:"Faculty of Law", school:"Monash Law School", level:3, creditPoints:6, semesters:["S1","S2"], campuses:["Clayton"], rating:3.9, reviewCount:103, difficulty:3, workload:"Moderate", description:"Formation, terms, breach, remedies, and vitiating factors of contracts. Core law unit.", tags:["law","contract","remedies","formation","clayton-only"] },
];

export const INITIAL_REVIEWS: Review[] = [
  { id:1,  unitCode:"FIT1045", author:"anon_4521", semester:"S1", year:2024, overallRating:4, difficulty:3, workload:"Moderate", teachingQuality:5, comment:"Great intro to programming. Labs well-structured, tutors super helpful. Assignments teach algorithmic thinking. Do all Ed practice exercises before the exam.", upvotes:34, hasUpvoted:false },
  { id:2,  unitCode:"FIT1045", author:"anon_7892", semester:"S2", year:2023, overallRating:3, difficulty:3, workload:"Moderate", teachingQuality:3, comment:"Decent intro but lectures feel slow if you already code. Final exam harder than expected — more edge cases than practice tests.", upvotes:18, hasUpvoted:false },
  { id:3,  unitCode:"FIT1045", author:"anon_1133", semester:"S1", year:2023, overallRating:5, difficulty:2, workload:"Light", teachingQuality:5, comment:"Came in with zero coding experience and left confident in Python. Ed forum incredibly active and team responds within hours.", upvotes:52, hasUpvoted:false },
  { id:4,  unitCode:"FIT2004", author:"anon_3301", semester:"S1", year:2024, overallRating:5, difficulty:5, workload:"Heavy", teachingQuality:5, comment:"Best unit in the IT faculty, full stop. Dense content but gold for technical interviews. Start every assignment the day it drops.", upvotes:89, hasUpvoted:false },
  { id:5,  unitCode:"FIT2004", author:"anon_5567", semester:"S2", year:2023, overallRating:4, difficulty:4, workload:"Heavy", teachingQuality:4, comment:"Hard but fair. Assignment 2 on graph algorithms took 35+ hours. Don't leave it two days before the deadline.", upvotes:41, hasUpvoted:false },
  { id:6,  unitCode:"ECF1100", author:"anon_2244", semester:"S1", year:2024, overallRating:4, difficulty:2, workload:"Light", teachingQuality:4, comment:"Very accessible. Slides comprehensive, MSTs straightforward if you attend tutorials. Solid WAM booster.", upvotes:27, hasUpvoted:false },
  { id:7,  unitCode:"FIT3170", author:"anon_9988", semester:"S1", year:2024, overallRating:5, difficulty:3, workload:"Heavy", teachingQuality:5, comment:"Most industry-relevant unit in the IT degree. Working with a real client is invaluable. Weekly scrums keep the team on track.", upvotes:63, hasUpvoted:false },
  { id:8,  unitCode:"PHY1011", author:"anon_6612", semester:"S2", year:2023, overallRating:3, difficulty:4, workload:"Heavy", teachingQuality:3, comment:"Content interesting but relentless pace. Labs well-designed. Exam is calculation-heavy — do every past paper.", upvotes:22, hasUpvoted:false },
  { id:9,  unitCode:"FIT2094", author:"anon_8814", semester:"S1", year:2024, overallRating:4, difficulty:3, workload:"Moderate", teachingQuality:4, comment:"Really enjoyable once SQL clicks. Assignments are practical. ERD modelling takes a few weeks to feel natural.", upvotes:31, hasUpvoted:false },
  { id:10, unitCode:"FIT3173", author:"anon_2291", semester:"S1", year:2024, overallRating:5, difficulty:4, workload:"Heavy", teachingQuality:5, comment:"CTF-style assignments are genuinely fun. If you're into security this is the best unit at Monash.", upvotes:58, hasUpvoted:false },
  { id:11, unitCode:"PSY1011", author:"anon_3341", semester:"S1", year:2024, overallRating:5, difficulty:2, workload:"Light", teachingQuality:5, comment:"Genuinely fascinating content. The biological bases section and perception topics were highlights. Great for any major as a breadth unit.", upvotes:71, hasUpvoted:false },
  { id:12, unitCode:"PSY3032", author:"anon_7729", semester:"S2", year:2023, overallRating:5, difficulty:3, workload:"Moderate", teachingQuality:5, comment:"One of the most engaging units I've taken at Monash. Case studies bring the content to life.", upvotes:44, hasUpvoted:false },
  { id:13, unitCode:"FIT1049", author:"anon_5590", semester:"S2", year:2023, overallRating:2, difficulty:1, workload:"Light", teachingQuality:2, comment:"Compulsory but not particularly useful. Essays and group presentations about ethics. Easy marks if you engage.", upvotes:44, hasUpvoted:false },
  { id:14, unitCode:"FIT3179", author:"anon_8823", semester:"S2", year:2024, overallRating:4, difficulty:2, workload:"Moderate", teachingQuality:4, comment:"Excellent unit for building your portfolio. D3.js and Vega-Lite are genuinely useful skills.", upvotes:38, hasUpvoted:false },
  { id:15, unitCode:"PHI1010", author:"anon_4417", semester:"S1", year:2024, overallRating:4, difficulty:2, workload:"Light", teachingQuality:4, comment:"Perfect breadth unit. Essay format suits the content, topics genuinely thought-provoking. No maths — refreshing if you're in STEM.", upvotes:29, hasUpvoted:false },
];
